# Generated by Django 2.2 on 2020-06-19 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=18)),
                ('username', models.CharField(blank=True, max_length=18, null=True)),
                ('avatar', models.CharField(blank=True, max_length=528, null=True, verbose_name='头像')),
                ('age', models.IntegerField(blank=True, null=True, verbose_name='年龄')),
                ('sex', models.SmallIntegerField(choices=[(1, '男'), (0, '女'), (2, '未知')], default=2)),
                ('introduce', models.TextField(blank=True, null=True)),
                ('create_time', models.DateTimeField(auto_now=True)),
                ('last_login_time', models.DateTimeField(auto_now_add=True)),
                ('is_delete', models.BooleanField(default=False)),
                ('active', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'tbl_user',
            },
        ),
    ]
