# Generated by Django 2.2 on 2020-06-19 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20200619_2058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='last_login_time',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
