// ============================================================================
// This is auto-generated by gf cli tool only once. Fill this file as you wish.
// ============================================================================

package auth_user_user_permissions

// Fill with you ideas below.